source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "kramdown"
gem "rouge"

# Avoid google-protobuf 4.x build failures with Ruby 3.1 on GitHub Actions.
gem "sass-embedded", "1.75.0"
gem "google-protobuf", "~> 3.25"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end
